### PR TITLE
Add Null-safety support

### PR DESCRIPTION
**Pull request by IchordeDionysos**
- This release adds null safety to the Braze SDK.
- This release also makes the `logEvent` and `logPurchase` (with `properties`) functions more idiomatic for Dart.

Currently, there are a few open questions on whether some fields should be nullable or not.
All questions are marked with a `todo: `.

Might make sense to get feedback on those question from you :)

### CODE REVIEW

**Comment by steven-spiel** [comment]
This would be really helpful for me! Thanks for working on it!

**Comment by hokstuff** [comment]
Hi @IchordeDionysos,

Thanks for the contribution and sorry for the delayed response! We are planning to integrate these changes into our next release. We'll review the changes internally and may make some edits - thanks for the head start! I'll keep this thread updated with progress as well as once it gets released.

Thank you!

**Comment by steven-spiel** [comment]
Any progress on the migration?

**Comment by hokstuff** [comment]
Hi @steven-spiel,

Thanks for checking in. This is the highest priority item we are working on for the Flutter SDK, and it is still in progress. I will hopefully have more information for you shortly - thank you for your patience!

**Comment by hokstuff** [comment]
Just wanted to give an update. We are now validating the changes included in this PR (alongside our other updates) and are hoping to release with this feature soon - thanks for waiting!

**Comment by hokstuff** [comment]
@IchordeDionysos @steven-spiel @alexander-dejeu @boucha98 and others watching,

We have just released our Braze Flutter SDK [version 2.0.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/2.0.0) which includes this PR's changes in our migration to null safety! Thank you for your contribution and helping push the SDK to use the latest Flutter technologies 🙂

Please let us know if you run into any issues! 🙏

Best,
Daniel

**Pull request closed without merging**
